/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postest4;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

/**
 *
 * @author Hijratul
 */
public class post extends javax.swing.JFrame {

    /**
     * Creates new form post
     */
    public post() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        JPanel2 = new javax.swing.JPanel();
        Next = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        PSatu = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        telp = new javax.swing.JLabel();
        berat = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        TFTelp = new javax.swing.JTextField();
        TFBerat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PDua = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        SliderDiskon = new javax.swing.JSlider();
        Reguler = new javax.swing.JRadioButton();
        Express = new javax.swing.JRadioButton();
        TFTotal = new javax.swing.JTextField();
        LSlider = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        Proses = new javax.swing.JButton();
        Ulangi = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(185, 236, 207));

        JPanel2.setBackground(new java.awt.Color(185, 236, 207));

        Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postest4/Arrows-Redo-icon.png"))); // NOI18N
        Next.setToolTipText("");
        Next.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NextMouseExited(evt);
            }
        });
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postest4/Arrows-Undo-icon.png"))); // NOI18N
        Back.setToolTipText("");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new java.awt.CardLayout());

        PSatu.setBackground(new java.awt.Color(185, 236, 207));

        nama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nama.setText("Nama");

        telp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        telp.setText("No. Telepon");

        berat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        berat.setText("Berat Barang");

        TFNama.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TFNama.setText("Masukkan Nama");
        TFNama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFNamaCaretUpdate(evt);
            }
        });

        TFTelp.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TFTelp.setText("Masukkan No.Telepon");
        TFTelp.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFTelpCaretUpdate(evt);
            }
        });
        TFTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTelpActionPerformed(evt);
            }
        });
        TFTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFTelpKeyPressed(evt);
            }
        });

        TFBerat.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TFBerat.setText("0");
        TFBerat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TFBeratCaretUpdate(evt);
            }
        });
        TFBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBeratActionPerformed(evt);
            }
        });
        TFBerat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TFBeratKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Kg");

        javax.swing.GroupLayout PSatuLayout = new javax.swing.GroupLayout(PSatu);
        PSatu.setLayout(PSatuLayout);
        PSatuLayout.setHorizontalGroup(
            PSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PSatuLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(PSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama)
                    .addComponent(telp)
                    .addComponent(berat))
                .addGap(25, 25, 25)
                .addGroup(PSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PSatuLayout.createSequentialGroup()
                        .addComponent(TFBerat, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addComponent(TFNama)
                    .addComponent(TFTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        PSatuLayout.setVerticalGroup(
            PSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PSatuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(PSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telp)
                    .addComponent(TFTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(PSatuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(berat)
                    .addComponent(TFBerat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(33, 33, 33))
        );

        jPanel5.add(PSatu, "card2");

        PDua.setBackground(new java.awt.Color(185, 236, 207));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Atur Diskon");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Jenis Jasa");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Total Harga");

        SliderDiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SliderDiskonStateChanged(evt);
            }
        });

        buttonGroup1.add(Reguler);
        Reguler.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Reguler.setText("Reguler");

        buttonGroup1.add(Express);
        Express.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Express.setText("Express");

        TFTotal.setEditable(false);
        TFTotal.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        TFTotal.setText("Total Harga");

        LSlider.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LSlider.setText("50%");

        javax.swing.GroupLayout PDuaLayout = new javax.swing.GroupLayout(PDua);
        PDua.setLayout(PDuaLayout);
        PDuaLayout.setHorizontalGroup(
            PDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDuaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(SliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LSlider)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(PDuaLayout.createSequentialGroup()
                .addGroup(PDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PDuaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addGap(32, 32, 32)
                        .addComponent(Reguler))
                    .addGroup(PDuaLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(Express))
                    .addGroup(PDuaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addGap(23, 23, 23)
                        .addComponent(TFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PDuaLayout.setVerticalGroup(
            PDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PDuaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PDuaLayout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(jLabel6))
                        .addComponent(SliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LSlider))
                .addGap(26, 26, 26)
                .addGroup(PDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PDuaLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel7))
                    .addComponent(Reguler))
                .addGap(17, 17, 17)
                .addComponent(Express)
                .addGap(18, 18, 18)
                .addGroup(PDuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PDuaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel8))
                    .addComponent(TFTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel5.add(PDua, "card3");

        javax.swing.GroupLayout JPanel2Layout = new javax.swing.GroupLayout(JPanel2);
        JPanel2.setLayout(JPanel2Layout);
        JPanel2Layout.setHorizontalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Next)
                .addContainerGap())
            .addGroup(JPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        JPanel2Layout.setVerticalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next)
                    .addComponent(Back)))
        );

        jPanel3.setBackground(new java.awt.Color(119, 119, 119));

        jLabel1.setBackground(new java.awt.Color(185, 236, 207));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM PELANGGAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jPanel4.setBackground(new java.awt.Color(119, 119, 119));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });
        jPanel4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel4KeyReleased(evt);
            }
        });

        Proses.setText("PROSES");
        Proses.setEnabled(false);
        Proses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProsesMouseExited(evt);
            }
        });
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });

        Ulangi.setText("ULANGI");
        Ulangi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UlangiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UlangiMouseExited(evt);
            }
        });
        Ulangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UlangiActionPerformed(evt);
            }
        });
        Ulangi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UlangiKeyReleased(evt);
            }
        });

        Keluar.setText("KELUAR");
        Keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                KeluarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                KeluarMousePressed(evt);
            }
        });
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Proses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ulangi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Proses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Ulangi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Keluar)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        TFNama.setText("");
        TFTelp.setText("");
        TFBerat.setText("");
        TFTotal.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        PDua.setVisible(true);
        PSatu.setVisible(false);
        Next.setVisible(false);
        Back.setVisible(true);
        
    }//GEN-LAST:event_NextActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        PSatu.setVisible(true);
        PDua.setVisible(false);
        Next.setVisible(true);
        Back.setVisible(false);
        
    }//GEN-LAST:event_BackActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_KeluarActionPerformed

    private void UlangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UlangiActionPerformed
        // TODO add your handling code here:
        TFNama.setText("");
        TFTelp.setText("");
        TFBerat.setText("");
        TFTotal.setText("Rp. ");
        buttonGroup1.clearSelection();
        SliderDiskon.setValue(0);
    }//GEN-LAST:event_UlangiActionPerformed

    private void SliderDiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SliderDiskonStateChanged
        // TODO add your handling code here:
        LSlider.setText(String.valueOf(SliderDiskon.getValue())+"%");
    }//GEN-LAST:event_SliderDiskonStateChanged

    private void TFTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTelpActionPerformed

    private void TFBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFBeratActionPerformed

    private void TFNamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFNamaCaretUpdate
        // TODO add your handling code here:
        if (TFNama.getText().length() !=0 && TFTelp.getText().length() !=0 && TFBerat.getText().length() !=0)
        {
           Proses.setEnabled(true);
        }
        else
        {    
            Proses.setEnabled(false);
        }
    }//GEN-LAST:event_TFNamaCaretUpdate

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        // TODO add your handling code here:
        Float bayar = null,jumlah,diskon;
        if(Reguler.isSelected()){
            diskon =Float.valueOf(SliderDiskon.getValue());
            jumlah = 11500*(Float.valueOf(TFBerat.getText()))-((diskon/100)*11500);
            bayar = jumlah; 
        }
        else if (Express.isSelected()){
             diskon = Float.valueOf(SliderDiskon.getValue());
             jumlah = 11500*(Float.valueOf(TFBerat.getText()))-((diskon/100)*11500);
             bayar = 1.5f*jumlah;
        }
        
        TFTotal.setText("Rp. "+bayar+"0");

    }//GEN-LAST:event_ProsesActionPerformed

    private void TFTelpCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFTelpCaretUpdate
        // TODO add your handling code here:
        if (TFNama.getText().length() !=0 && TFTelp.getText().length() !=0 && TFBerat.getText().length() !=0)
        {
           Proses.setEnabled(true);
        }
        else
        {    
            Proses.setEnabled(false);
        }
    }//GEN-LAST:event_TFTelpCaretUpdate

    private void TFBeratCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TFBeratCaretUpdate
        // TODO add your handling code here:
        if (TFNama.getText().length() !=0 && TFTelp.getText().length() !=0 && TFBerat.getText().length() !=0)
        {
           Proses.setEnabled(true);
        }
        else
        {    
            Proses.setEnabled(false);
        }
    }//GEN-LAST:event_TFBeratCaretUpdate

    private void KeluarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_KeluarMousePressed

    private void KeluarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KeluarMouseEntered
        // TODO add your handling code here:
        Keluar.setBackground(Color.cyan);
        Keluar.setForeground(Color.BLACK);
    }//GEN-LAST:event_KeluarMouseEntered

    private void UlangiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UlangiMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_UlangiMouseExited

    private void ProsesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProsesMouseExited
        // TODO add your handling code here:
        Proses.setBackground(Color.CYAN);
        Proses.setForeground(Color.BLACK);
    }//GEN-LAST:event_ProsesMouseExited

    private void NextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NextMouseEntered

    private void NextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextMouseExited
        // TODO add your handling code here:
        Next.setBackground(Color.CYAN);
        Next.setForeground(Color.BLACK);
    }//GEN-LAST:event_NextMouseExited

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        Back.setBackground(Color.CYAN);
        Back.setForeground(Color.BLACK);
    }//GEN-LAST:event_BackMouseExited

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        // TODO add your handling code here:
        Proses.setBackground(Color.PINK);
        Proses.setForeground(Color.BLACK);
    }//GEN-LAST:event_formMouseExited

    private void UlangiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UlangiMouseEntered
        // TODO add your handling code here:
        Ulangi.setBackground(Color.cyan);
        Ulangi.setForeground(Color.BLACK);
    }//GEN-LAST:event_UlangiMouseEntered

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel4KeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel4KeyReleased

    private void UlangiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UlangiKeyReleased

    }//GEN-LAST:event_UlangiKeyReleased

    private void TFTelpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFTelpKeyPressed
        // TODO add your handling code here:
        TFTelp.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
            char angka= e.getKeyChar();
            if(!((angka >='0') && (angka <='9') || (angka == '\b'))){
                e.consume();
            }
            }
        });   
    }//GEN-LAST:event_TFTelpKeyPressed

    private void TFBeratKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFBeratKeyPressed
        // TODO add your handling code here:
        TFBerat.addKeyListener(new KeyAdapter(){
            public void keyTyped(KeyEvent e){
            char angka= e.getKeyChar();
            if(!((angka >='0') && (angka <='9')|| (angka == '\b'))){
                e.consume();
            }
            }
        });   
    }//GEN-LAST:event_TFBeratKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new post().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JRadioButton Express;
    private javax.swing.JPanel JPanel2;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel LSlider;
    private javax.swing.JButton Next;
    private javax.swing.JPanel PDua;
    private javax.swing.JPanel PSatu;
    private javax.swing.JButton Proses;
    private javax.swing.JRadioButton Reguler;
    private javax.swing.JSlider SliderDiskon;
    private javax.swing.JTextField TFBerat;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFTelp;
    private javax.swing.JTextField TFTotal;
    private javax.swing.JButton Ulangi;
    private javax.swing.JLabel berat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel telp;
    // End of variables declaration//GEN-END:variables
}
